kind: PersistentVolume
apiVersion: v1
metadata:
  name: mypv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    pdName: pvdisk 
    fsType: ext4
